# Generated by Django 4.2.17 on 2024-12-09 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("Watching", "Watching"),
                            ("Completed", "Completed"),
                            ("On Hold", "On Hold"),
                            ("Dropped", "Dropped"),
                            ("Plan to Watch", "Plan to Watch"),
                        ],
                        default="Plan to Watch",
                        max_length=20,
                    ),
                ),
                ("synopsis", models.TextField()),
                ("anime_score", models.IntegerField()),
                ("anime_id", models.IntegerField()),
                ("anime_poster", models.CharField(max_length=100)),
                ("episodes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("airing_status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
