import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/Navbar";
import PrelineScriptWrapper from "./ui/PrelineScriptWrapper";
import SideBar from "./ui/SideBar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={""}>
				<div>
					<div className="z-50">
						<Navbar />
					</div>
					<div className="flex">
						{/* <div className="hidden lg:block w-[80px] shadow-md fixed top-[65px] left-0 h-screen"> */}
						<div className="hidden z-0 lg:block w-20 shadow-md fixed top-16.25 left-0 h-[calc(100vh-65px)]">
							<SideBar />
						</div>
						<div className="w-full mt-16.25 z-10 lg:ml-21.25">
							<div>{children}</div>
						</div>
					</div>
				</div>
			</body>
			<PrelineScriptWrapper />
		</html>
	);
}
